In [54]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [55]:
list_1 = [1,2,3,4]

In [56]:
a=np.array(list_1)

In [57]:
a

array([1, 2, 3, 4])

In [11]:
b=np.array([[1,2,3],[4,5,6]])

In [12]:
print (b.shape)

(2, 3)


In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
list=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [25]:
arr = np.array(list)

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a=arr[1:,1:]

In [31]:
print(a)

[[5 6]
 [8 9]]


In [35]:
a=arr[0:,2:]

In [37]:
print(a)

[[3]
 [6]
 [9]]


In [39]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [44]:
bool_array

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [47]:
n=arr[bool_array]
n

array([2, 4, 6, 8])

In [50]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [53]:
a=np.array(list)
bool_indexing=(a%2==0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]
